/* The framework as DATA - the single copy the platform runs on.
   Extracted verbatim from the assessor tool (public/assessor/dashboard.html) on 13 Sep 2026;
   the tool's copy is the one to retire, this is the one to edit. v0.6 set (unchanged since v0.5).
   Nothing here touches the DOM or a database. */

export const FRAMEWORK_VERSION='0.6';

export const INDICATORS = [
 {id:'1.1.1',std:1,m:1,st:2,t:'Outcomes learner-facing, observable and assessable'},
 {id:'1.1.2',std:1,m:1,st:2,t:'Level of demand stated; content, assessment and hours aligned to it'},
 {id:'1.1.3',std:1,m:1,st:2,t:'Full outcome-content-assessment mapping matrix supplied and verified'},
 {id:'1.2.1',std:1,m:1,st:2,t:'Provider warranty of accuracy and lawfulness in the submission'},
 {id:'1.2.2',std:1,m:1,st:2,t:'Named SME sign-off - credentials verified, dated and current'},
 {id:'1.2.3',std:1,m:1,st:2,t:'Substantive claims attributed to identifiable, traceable sources - presence checked, never correctness'},
 {id:'1.2.4',std:1,m:1,st:2,t:'Review cycle stated (24 months max), named owner, visible reviewed-on date'},
 {id:'1.3.1',std:1,m:1,st:2,t:'Title, marketing and certificate claim no more than the outcomes deliver'},
 {id:'1.3.2',std:1,m:1,st:2,t:'Limits stated plainly'},
 {id:'1.4.1',std:1,m:1,st:2,t:'Hours are notional learning time, not seat time or padding'},
 {id:'1.4.2',std:1,m:1,st:2,t:'Hours calculation shown in full, evidenced'},
 {id:'1.4.3',std:1,m:1,st:4,t:'Stated hours within 20% of the independent derivation'},
 {id:'1.5.1',std:1,m:0,st:2,t:'Units chunked and structured; open with coverage, close with consolidation'},
 {id:'1.5.2',std:1,m:0,st:2,t:'Prerequisites stated; concepts before use; jargon defined at first use'},
 {id:'1.5.3',std:1,m:0,st:2,t:'Worked examples connect to the learner\'s work context'},
 {id:'1.6.1',std:1,m:0,st:2,t:'Audience defined: role, sector, prior knowledge'},
 {id:'1.6.2',std:1,m:0,st:2,t:'Design decisions demonstrably matched to that audience'},
 {id:'2.1.1',std:2,m:1,st:2,t:'Credible rationale: methods suit the outcomes and audience'},
 {id:'2.1.2',std:2,m:1,st:2,t:'Method matches claim - application outcomes get application practice'},
 {id:'2.2.1',std:2,m:1,st:2,t:'Subject competence evidenced for every named educator, author, designer'},
 {id:'2.2.2',std:2,m:1,st:2,t:'Teaching capability evidenced for the same people'},
 {id:'2.3.1',std:2,m:0,st:3,t:'Meaningful learner activity at regular intervals - no click-theatre'},
 {id:'2.3.2',std:2,m:0,st:3,t:'Spacing and retrieval: key concepts recur (activities over ~2 hours)'},
 {id:'2.4.1',std:2,m:0,st:3,mode:'el',t:'E-learning: fully functional on desktop and mobile'},
 {id:'2.4.2',std:2,m:0,st:3,mode:'el',t:'E-learning: pause, resume, navigate back; media has player controls'},
 {id:'2.4.3',std:2,m:0,st:3,mode:'el',t:'E-learning: no forced timers standing in for learning design'},
 {id:'2.4.4',std:2,m:0,st:3,mode:'lo',t:'Live online: interaction plan real, presenter ratio realistic'},
 {id:'2.4.5',std:2,m:0,st:3,mode:'lo',t:'Live online: breaks past 60 minutes; joining instructions in advance'},
 {id:'2.4.6',std:2,m:0,st:3,mode:'f2f',t:'Face-to-face: session plan with timings and methods'},
 {id:'2.4.7',std:2,m:0,st:3,mode:'f2f',t:'Face-to-face: group size justified; venue and equipment documented'},
 {id:'2.4.8',std:2,m:0,st:3,mode:'bl',t:'Blended: components integrated, not bundled'},
 {id:'2.5.1',std:2,m:0,st:3,t:'Content-question route tested for real against the stated commitment'},
 {id:'2.5.2',std:2,m:0,st:3,t:'Technical-problem route tested for real'},
 {id:'3.1.1',std:3,m:0,st:2,t:'Plain English: active voice, short sentences, one idea per sentence'},
 {id:'3.1.2',std:3,m:1,st:2,t:'Readability checked, method stated, score in submission, fits audience'},
 {id:'3.1.3',std:3,m:1,st:2,t:'No more than 3 minor errors in sample; zero in headings, outcomes, certificates'},
 {id:'3.1.4',std:3,m:0,st:2,t:'Consistent terminology throughout'},
 {id:'3.2.1',std:3,m:1,st:2,t:'Two-person editorial chain evidenced: names, dates, version history'},
 {id:'3.2.2',std:3,m:0,st:2,t:'Style guide exists and the material follows it'},
 {id:'3.3.1',std:3,m:1,st:2,t:'WCAG 2.2 AA: contrast, keyboard, focus, resizable text, colour'},
 {id:'3.3.2',std:3,m:1,st:2,t:'Captions, transcripts, alt text, tagged documents (re-verified live)'},
 {id:'3.3.3',std:3,m:0,st:2,t:'Print/slide legibility floor: text size, type, spacing'},
 {id:'3.3.4',std:3,m:1,st:2,t:'Accessibility statement: what is supported, how to request adjustments'},
 {id:'3.4.1',std:3,m:0,st:2,t:'Slides support learning: one idea, honest charts, labelled diagrams'},
 {id:'3.4.2',std:3,m:0,st:2,t:'Consistent visual system: hierarchy, colour, iconography'},
 {id:'3.4.3',std:3,m:1,st:2,t:'Third-party media licensed; attribution where the licence requires'},
 {id:'3.5.1',std:3,m:0,st:2,t:'Inclusive examples and imagery; respectful across protected characteristics'},
 {id:'3.5.2',std:3,m:0,st:2,t:'Jurisdictional scope stated where England/Wales/Scotland/NI requirements differ'},
 {id:'4.1.1',std:4,m:1,st:2,cond:'assess',t:'Every item maps to an outcome; bank covers all assessed outcomes'},
 {id:'4.1.2',std:4,m:1,st:2,cond:'assess',t:'Items test at outcome level; no trick or ambiguous items'},
 {id:'4.1.3',std:4,m:1,st:2,cond:'assess',t:'Pass mark justified and the setting method explained'},
 {id:'4.2.1',std:4,m:0,st:2,cond:'assess',t:'Pools/randomisation make retakes meaningful; retake policy stated'},
 {id:'4.2.2',std:4,m:0,st:2,cond:'assess',t:'Human-marked assessment has rubrics and standardisation'},
 {id:'4.3.1',std:4,m:1,st:2,cond:'cert',t:'Certificate content complete, with unique verifiable ID'},
 {id:'4.3.2',std:4,m:1,st:2,cond:'cert',t:'No implication of regulated status, licence to practise, or over-claim'},
 {id:'4.3.3',std:4,m:1,st:2,cond:'cert',t:'Attendance vs achievement wording correct for what was measured'},
 {id:'4.4.1',std:4,m:0,st:2,cond:'cert',t:'Anti-fraud controls proportionate to certificate stakes'},
 {id:'5.1.1',std:5,m:1,st:2,t:'Structured feedback every cohort: relevance, clarity, engagement, confidence'},
 {id:'5.1.2',std:5,m:1,st:2,t:'Response rates and results retained, available at surveillance'},
 {id:'5.2.1',std:5,m:0,st:2,t:'Beyond-satisfaction measure attempted for substantial activities'},
 {id:'5.3.1',std:5,m:0,st:2,t:'Documented feedback-to-change loop, with examples'},
 {id:'5.4.1',std:5,m:1,st:2,t:'Complaints procedure published, with timescales'},
 {id:'5.4.2',std:5,m:1,st:2,t:'Fair refund policy published'},
 {id:'5.4.3',std:5,m:1,st:2,t:'Complaint records kept and available'},
 {id:'6.1.1',std:6,m:1,st:2,t:'Registered entity, verifiable address, named responsible person'},
 {id:'6.1.2',std:6,m:1,st:2,t:'Insurance in place: PI, and PL where delivering in person'},
 {id:'6.1.3',std:6,m:1,st:2,t:'Principals\' declarations clean: convictions, regulatory findings'},
 {id:'6.2.1',std:6,m:1,st:2,t:'ICO registration where required; privacy notice covers learner data'},
 {id:'6.2.2',std:6,m:1,st:2,t:'Secure learner records; min 3-year retention for certificated learning'},
 {id:'6.3.1',std:6,m:1,st:2,t:'Marketing claims about the activity and its recognition are accurate'},
 {id:'6.3.2',std:6,m:1,st:2,t:'Mark used only in scope and within the validity period'},
 {id:'6.3.3',std:6,m:1,st:2,t:'No claim implies the scheme verified or endorsed content truth (A5)'},
 {id:'6.4.1',std:6,m:0,st:2,t:'Capacity to deliver at the advertised scale'},
 {id:'6.4.2',std:6,m:0,st:2,t:'Continuity plan for learners in flight if the provider ceases trading'}
];

export const STD_NAMES = {1:'Learning design & content quality',2:'Teaching & delivery methods',3:'Writing & presentation standards',4:'Assessment & certification integrity',5:'Learner experience & outcomes',6:'Organisational fitness'};

export const MODERATION = [
 ['MOD-1','Every score has cited evidence - any "looks fine" score bounced back'],
 ['MOD-2','Every N/A has a stated reason and is genuinely inapplicable'],
 ['MOD-3','No partial credit sits on any mandatory indicator'],
 ['MOD-4','Borderline Met/Partial calls sampled and re-scored blind'],
 ['MOD-5','Every mandatory failure double-checked and flagged early to the provider'],
 ['MOD-6','Draft decision computed from rules C2 - arithmetic plus gates, not mood']
];

export const SOURCES = {
  'STAGE-1':[{s:'Scheme methodology C1 - application & completeness',why:'A coordinator confirms the submission is assessable before any judgement is made.'},{s:'Ofqual General Conditions of Recognition - conflict of interest',why:'Conflicted assessors are screened out before allocation.'}],
  'STAGE-2':[{s:'Scheme methodology C1 - desk review',why:'The assessor completes the whole activity as a learner, not a provider-chosen sample.'},{s:'Principle A3 - Validity',why:'Confirms the activity teaches what it claims, scored indicator by indicator.'}],
  'STAGE-3':[{s:'Scheme methodology C1 - live verification',why:'Observation and a mystery-learner pass test what actually happens, not just the script.'},{s:'Mystery-shopping & observation practice',why:'Advertised learner-support routes are tested for real.'}],
  'STAGE-4':[{s:'Scheme methodology C1 - independent derivations',why:'CPD hours and assessment coverage are re-derived, never taken on trust.'},{s:'CIPD / professional-body CPD - notional learning time',why:'The hours are recalculated against notional learning time.'}],
  'STAGE-5':[{s:'Ofqual GCoR - reliability & standardisation',why:'A second assessor moderates so two assessors reach the same decision.'},{s:'Scheme methodology C3 - inter-assessor reliability',why:'Calibration and blind double-scoring keep decisions consistent.'}],
  'STAGE-6':[{s:'Scheme decision rules C2',why:'Outcome is computed from gates plus points; one deferral, eight weeks, then final.'},{s:'Anti-logo-shop principle A1',why:'Refusal is a real outcome; we never sell help to pass our own assessment.'}],
  'STAGE-7':[{s:'Scheme D5 - public register & verification',why:'A pass is listed with its exact scope and a verifiable certificate ID.'},{s:'Scheme D3 appeals & D6 transparency report',why:'A refusal carries an appeal route and feeds published statistics.'}],
  'STAGE-8':[{s:'Scheme methodology C4 - cycle & surveillance',why:'Annual surveillance with revocation is what separates accreditation from a subscription.'},{s:'ISO 21001 / ISO 29993 - audit cycle',why:'Regulated-sector schemes monitor between renewals; a one-off check drifts immediately.'}],

  '1.1':[{s:'Constructive alignment (Biggs & Tang)',why:'Outcomes, content and assessment must line up.'},{s:'Bloom’s taxonomy (revised)',why:'Defines the levels of demand - awareness / working knowledge / application / analysis.'}],
  '1.1.3':[{s:'Assessment blueprinting (Ofqual-style outcome mapping)',why:'The evidence matrix maps every outcome to content and to assessment.'},{s:'Constructive alignment (Biggs & Tang)',why:'No orphaned content, no uncovered outcome.'}],
  '1.2':[{s:'Scheme scope boundary A5',why:'We assess the accuracy-assurance PROCESS, never the truth of the content.'},{s:'Professional content governance (SME sign-off, review cycles)',why:'Standard QA for keeping subject content credible and current.'}],
  '1.2.1':[{s:'Accreditation agreement (Part F legal)',why:'The provider warrants accuracy and lawfulness and indemnifies the scheme.'},{s:'Scheme scope boundary A5',why:'Responsibility for the facts stays entirely with the provider.'}],
  '1.3':[{s:'ASA / CAP advertising codes - no misleading claims',why:'Titles and certificates claim no more than the outcomes deliver.'},{s:'Scheme scope boundary A5',why:'No implication of regulated-qualification status.'}],
  '1.4':[{s:'CIPD / professional-body CPD definitions',why:'CPD hours are notional learning time, not seat time or marketing inflation.'}],
  '1.4.3':[{s:'Scheme decision rules C2 - 20% tolerance',why:'A claim more than 20% above the assessor’s derivation fails - stops hour inflation.'},{s:'CIPD notional learning time',why:'The benchmark the derivation is measured against.'}],
  '1.5':[{s:'Cognitive load theory (Sweller)',why:'Chunking and staged concepts keep material learnable.'},{s:'Instructional design (Gagné’s events of instruction)',why:'Units open with coverage and close with consolidation.'}],
  '1.6':[{s:'Training needs analysis / ADDIE (Analysis phase)',why:'Design decisions must be matched to a defined audience.'}],

  '2.1':[{s:'Constructive alignment & active-learning research',why:'Methods must fit the outcomes; passive design cannot claim application-level learning.'}],
  '2.2':[{s:'ETF Professional Standards (Education & Training Foundation)',why:'Educators need dual competence - subject knowledge AND teaching capability.'}],
  '2.3':[{s:'Retrieval practice & spacing (cognitive science)',why:'Meaningful activity and recurring retrieval, not click-to-continue.'},{s:'Active-learning research (Freeman et al., 2014)',why:'Learners doing outperforms learners watching.'}],
  '2.4':[{s:'Adult learning / andragogy (Knowles)',why:'Session design suited to adult learners and the delivery mode.'},{s:'E-learning & live-online facilitation good practice',why:'Mode-specific functionality, breaks and interaction plans.'}],
  '2.5':[{s:'ISO 29993 - learning services outside formal education',why:'Defined, tested learner-support routes.'}],

  '3.1':[{s:'Plain English (Plain English Campaign / GOV.UK content design)',why:'Clear, active, jargon-light writing for the stated audience.'}],
  '3.1.2':[{s:'Readability formulas (Flesch Reading Ease, SMOG)',why:'Readability is measured with a stated method and the score recorded.'}],
  '3.2':[{s:'Editorial QA chain (author → technical review → proofread)',why:'Professional publishing governance, evidenced with names and dates.'}],
  '3.3':[{s:'WCAG 2.2 AA (W3C)',why:'The accessibility floor for all digital learning material.'}],
  '3.3.4':[{s:'Equality Act 2010 - reasonable adjustments',why:'An accessibility statement tells learners what is supported and how to ask.'},{s:'WCAG 2.2 AA (W3C)',why:'The technical baseline the statement reports against.'}],
  '3.4':[{s:'Multimedia learning principles (Mayer)',why:'Slides support learning; they are not the script.'},{s:'Media licensing / IP law',why:'Third-party images, fonts and media must be licensed.'}],
  '3.5':[{s:'Equality Act 2010 - protected characteristics',why:'Inclusive, respectful content across the workforce.'},{s:'UK four-nations legal differences',why:'Jurisdictional scope stated where requirements differ.'}],

  '4.1':[{s:'Ofqual GCoR - validity & standard-setting',why:'Items map to outcomes at the right level; pass marks are justified.'},{s:'Assessment blueprinting',why:'The item bank collectively covers all assessed outcomes.'}],
  '4.2':[{s:'Ofqual GCoR - reliability',why:'Meaningful retakes and marking standardisation.'},{s:'Psychometric good practice',why:'Item pools and randomisation.'}],
  '4.3':[{s:'Ofqual GCoR - certification',why:'Certificates carry verifiable, non-over-claiming information.'},{s:'Verifiable-credentials practice',why:'Unique IDs resolving to a live verification record.'}],
  '4.4':[{s:'Risk-based / proportionate assurance',why:'Anti-fraud controls scale with how the certificate will be used.'}],

  '5.1':[{s:'Kirkpatrick Level 1 (reaction)',why:'Structured learner feedback collected every cohort.'},{s:'ISO 21001 - educational management systems',why:'Monitoring learner satisfaction.'}],
  '5.2':[{s:'Kirkpatrick Levels 2-3 (learning / behaviour)',why:'Substantial activities go beyond satisfaction scores.'}],
  '5.3':[{s:'ISO 21001 continual improvement (Plan-Do-Check-Act)',why:'A documented loop from feedback to real content change.'},{s:'Principle A3 - continuous improvement',why:'Feedback must produce action, checked at surveillance.'}],
  '5.4':[{s:'Consumer Rights Act 2015 / ISO 21001',why:'Published complaints procedure and fair refunds.'}],

  '6.1':[{s:'ISO 21001 / ISO 29993 - organisational requirements',why:'A real, insured, accountable legal entity.'}],
  '6.2':[{s:'UK GDPR & Data Protection Act 2018',why:'ICO registration, privacy notice and secure learner records.'}],
  '6.3':[{s:'ASA / CAP advertising codes',why:'Marketing claims about the activity are accurate.'},{s:'Scheme mark-use rules (Part D4) + A5',why:'The mark is never used to imply the scheme verified content.'}],
  '6.4':[{s:'ISO 21001 - resources & continuity',why:'Capacity to deliver, and learner protection if the provider ceases trading.'}],

  'COMP':[{s:'Scheme methodology C1 - application & completeness',why:'A submission must be complete and assessable before scoring begins.'}],
  'C-11':[{s:'Ofqual GCoR - conflict of interest',why:'Conflicted assessors are screened out before allocation.'}],
  'MOD':[{s:'Ofqual GCoR - reliability & standardisation',why:'Second-assessor moderation before any decision exists.'},{s:'Scheme methodology C3',why:'Calibration and blind double-scoring keep assessors consistent.'}],
  'SV':[{s:'Scheme methodology C4 - annual surveillance',why:'The provider submits feedback data, complaints log, change log and current materials every year; the assessor samples for drift.'},{s:'Scheme C4 - change notification (28 days)',why:'Material changes must be notified within 28 days; unnotified drift is what surveillance exists to catch.'}]
};

export const GUIDANCE = {
 '1.1.1':{look:'Outcome statements phrased as what the LEARNER will be able to do afterwards, using verbs you could observe or test - "apply", "identify", "calculate" - not fuzzy ones like "understand", "appreciate" or "be aware of".',
  steps:['Find the published outcomes (sales page and materials - they must match)','Check each starts with an observable action verb','For each, ask: could I write a question that shows this happened?','Flag any outcome no assessment could ever confirm']},
 '1.1.2':{look:'The provider names a level of demand (awareness / working knowledge / application / analysis) and the content depth, assessment difficulty and hours all sit at that same level.',
  steps:['Find the stated level','Sample content: does an "application" course include practice, or just reading?','Check assessment items demand that level, not one below','Sanity-check the hours fit the claimed depth']},
 '1.1.3':{look:'A matrix (table) connecting every outcome to where it is taught and where it is assessed. No content that serves no outcome; no outcome without assessment coverage.',
  steps:['Locate the matrix in the submission','Pick 2-3 outcomes and follow them to content and assessment','Pick 2-3 content units and confirm each serves an outcome','Flag orphaned content or uncovered outcomes']},
 '1.2.1':{look:'A signed legal warranty in the pack: the provider takes full responsibility that their content is accurate and lawful. This is what keeps content liability with them, not us.',
  steps:['Find the signed warranty document','Check the signatory has authority (director or owner)','Check the wording covers both accuracy AND lawfulness','Check it is dated and covers this version of the material']},
 '1.2.2':{look:'A named subject-matter expert has signed off this version: name, credentials, date. You verify the credentials EXIST and the sign-off is current - you never judge the subject matter yourself.',
  steps:['Confirm name, role and credentials are stated','Verify the credentials are real (professional register, employer, public profile)','Check the sign-off date covers this version and is inside the review cycle']},
 '1.2.3':{look:'Substantive claims (legal, statistical, safety-critical) each carry an attribution you could follow to a real source. Presence and traceability ONLY - whether the source is right or current is the provider\'s SME\'s job, never ours (A5).',
  steps:['Sample the substantive claims across the material','Check each has an identifiable source (named document, body, date - not "studies show")','Record findings only as "no source attributed" - never "source is wrong or outdated"']},
 '1.2.4':{look:'A stated review cycle of 24 months or less, a named person who owns it, and a visible reviewed-on date so learners can tell the material is maintained.',
  steps:['Find the review policy or statement','Check the cycle length is stated and 24 months or under','Check a named owner is attached','Check the material shows when it was last reviewed']},
 '1.3.1':{look:'Read the title, the sales page and the certificate side by side with the outcomes list. Everything promised must actually be delivered by an outcome - no "masterclass" or "become an expert" on an awareness course.',
  steps:['List every promise the title and marketing make','Compare each promise against an actual outcome','Check the certificate wording claims no more than the outcomes','Flag anything promised but not delivered']},
 '1.3.2':{look:'A plain statement of what the activity does NOT do - not a regulated qualification, not a licence to practise, awareness-only - placed where a buyer sees it before paying.',
  steps:['Look for the limits statement','Check it is in plain language, not buried in terms','Check it appears pre-purchase, not only inside the course']},
 '1.4.1':{look:'The claimed hours are notional learning time - the total time a typical learner needs for content, activities and assessment - not video runtime, seat time or padding.',
  steps:['Read the hours claim and what the provider says it includes','Check nothing non-learning is counted (breaks, admin, upselling)','Cross-check against your own feel for the material as you complete it']},
 '1.4.2':{look:'The full arithmetic behind the hours claim, itemised: content time, activity time, assessment time. If you cannot re-trace the sum, it is not "shown in full".',
  steps:['Find the calculation document (C-06)','Check every component is itemised','Check the arithmetic actually adds to the claimed total']},
 '1.4.3':{look:'Your own independent re-derivation of the hours, done in Stage 4. The tool compares automatically: a claim more than 20% above your derivation fails this gate on the spot.',
  steps:['Complete the derivation in Stage 4 (word counts, media durations, activity timings)','The 20% check applies automatically','If it fails, share your arithmetic with the provider - it is a dispute about numbers, not opinion']},
 '1.5.1':{look:'Material split into digestible units. Each unit opens by saying what it covers and closes with a recap or consolidation - not an unbroken wall of content.',
  steps:['Scan the overall structure for chunking','Sample one unit\'s opening and one\'s closing','Flag long unbroken runs with no waypoints']},
 '1.5.2':{look:'Prerequisites stated up front, concepts taught before they are used, and jargon defined the first time it appears.',
  steps:['Check for a prerequisites statement','Sample early sections for undefined terms','Note any concept relied on before it is taught']},
 '1.5.3':{look:'Worked examples set in the learner\'s actual work context (the audience defined in 1.6.1) - not generic or academic cases that leave the learner to translate.',
  steps:['Sample the examples across the material','Check they reference the audience\'s real tasks and settings','Flag examples that only make sense outside the stated audience']},
 '1.6.1':{look:'A stated audience: role, sector and assumed prior knowledge. Specific enough that you could design against it - "anyone interested in food safety" is not an audience.',
  steps:['Find the audience statement','Check all three elements are present: role, sector, prior knowledge','Judge whether it is specific enough to drive design decisions']},
 '1.6.2':{look:'Evidence that the design actually follows from that audience - mode, depth, examples and length all make sense for those learners specifically.',
  steps:['Pick 2-3 visible design decisions (mode, depth, examples, duration)','Ask whether each makes sense for the stated audience','Look for the provider\'s own rationale connecting the two']},
 '2.1.1':{look:'The provider\'s explanation of WHY these teaching methods suit these outcomes and this audience. Generic "engaging and interactive" boilerplate is not a rationale.',
  steps:['Find the stated rationale','Check it names the actual methods used','Check it connects each method to outcomes or audience, not just adjectives']},
 '2.1.2':{look:'Where an outcome claims application or analysis, the learner must actually PRACTISE it - scenarios, decisions, exercises. Watching a video then answering recall questions cannot deliver "apply".',
  steps:['List the application/analysis-level outcomes','For each, find where the learner practises that skill','Flag any application claim served only by passive content']},
 '2.2.1':{look:'Every person named as educator, author or designer has evidenced subject credentials in the CV pack. You verify the evidence EXISTS - you never judge the subject matter itself.',
  steps:['List every name credited in the materials','Match each against the CV pack (C-07)','Check each CV shows relevant subject background','Flag anyone uncredentialed or missing']},
 '2.2.2':{look:'The same people also have TEACHING capability - qualifications, experience or observed practice. Knowing the subject is not the same as being able to teach it.',
  steps:['Re-check each CV for the teaching side: qualifications, facilitation experience, instructional-design work','Flag anyone with subject depth but no teaching evidence']},
 '2.3.1':{look:'As you complete the activity, the learner is regularly asked to DO something meaningful - answer, decide, practise - not just click Next. Activities must require thought to complete.',
  steps:['Complete the activity as a learner (Stage 3)','Log each genuine activity and the gaps between them','Ask of each: could I pass this without thinking?']},
 '2.3.2':{look:'For activities over about 2 hours: key concepts come back later - recaps, questions on earlier material - rather than being covered once and left.',
  steps:['Track 2-3 key concepts from early in the activity','Check whether they recur later (retrieval moments, cumulative questions)','Flag pure one-pass coverage on long activities']},
 '2.4.1':{look:'The e-learning genuinely works on both desktop and mobile: layout, media, interactions.',
  steps:['Run the module on a desktop browser','Run it again on a phone','Note broken layouts, unplayable media, dead controls']},
 '2.4.2':{look:'The learner can pause, resume where they left off, and navigate back to review; audio and video have player controls.',
  steps:['Close the module mid-way, reopen, check it resumes','Navigate backwards to earlier content','Check media players expose pause/scrub controls']},
 '2.4.3':{look:'No forced minimum-time locks standing in for learning design. A timer that just delays the Next button is padding, not pedagogy.',
  steps:['Watch for screens that lock progress on a timer','If timers exist, ask what learning purpose each serves','Flag timers whose only function is to inflate duration']},
 '2.4.4':{look:'A real interaction plan for the live session (polls, breakouts, Q&A rhythm) and a presenter-to-learner ratio that could actually deliver it.',
  steps:['Read the session plan for planned interactions per hour','Check the advertised maximum attendance','Sanity-check the two together - one presenter and 200 learners cannot run "group discussion"']},
 '2.4.5':{look:'Sessions running past 60 minutes schedule breaks, and joining instructions go out in advance so learners arrive ready.',
  steps:['Check the schedule for breaks past the hour mark','Check what joining information is sent and when']},
 '2.4.6':{look:'A written face-to-face session plan with timings and the teaching method for each segment.',
  steps:['Check the plan exists and covers the whole session','Check each block has a timing and a named method']},
 '2.4.7':{look:'The maximum group size is justified against the methods used, and the venue and equipment needs are documented.',
  steps:['Find the stated maximum group size','Ask whether the planned methods work at that size','Check the venue and equipment list exists']},
 '2.4.8':{look:'The blended components genuinely build on each other - the e-learning prepares for the live part, the live part uses it - rather than two products sold as one.',
  steps:['Look for cross-references between components','Check for a shared thread: one assessment, one progression','Flag components that never mention each other']},
 '2.5.1':{look:'The advertised route for content questions, tested for real. You send a genuine question as a learner and time the answer against the stated commitment.',
  steps:['Find the stated support commitment (route and response time)','Send a plausible content question as a learner','Time and judge the response against the commitment']},
 '2.5.2':{look:'Same test for technical problems - the advertised route, tried for real.',
  steps:['Report a plausible technical issue via the advertised route','Time and judge the response against the stated commitment']},
 '3.1.1':{look:'Plain-English writing: active voice, short sentences, one idea per sentence, for the stated audience.',
  steps:['Sample several pages across the material','Flag long passive multi-clause sentences','If a sentence halves when you rewrite it in your head, note it']},
 '3.1.2':{look:'The provider states which readability method they used (Flesch, SMOG...) and the score, and the score suits the stated audience.',
  steps:['Find the stated method and score (C-08)','Run a sample yourself to spot-check the score','Judge the level against the stated audience']},
 '3.1.3':{look:'Your proofing sample: no more than 3 minor errors, and ZERO in headings, outcomes and certificates - the places an employer will actually read.',
  steps:['Proof a defined sample of the material','Count and log errors found','Check headings, outcome statements and the certificate are word-perfect']},
 '3.1.4':{look:'The same thing is called the same name all the way through - no drifting between "module"/"unit" or "customer"/"client".',
  steps:['Pick 2-3 key terms','Scan for synonym drift across the material','Flag renames that could confuse a learner']},
 '3.2.1':{look:'At least two different people touched the material - author plus reviewer/proofreader - evidenced with names, dates and version history.',
  steps:['Find the QA record or version history','Check different names appear at each step','Check the dates run in a sensible order']},
 '3.2.2':{look:'A style guide exists and the material visibly follows it.',
  steps:['Check the guide exists','Pick 2-3 of its rules and sample the material against them']},
 '3.3.1':{look:'The WCAG 2.2 AA basics: colour contrast, keyboard operability, visible focus, resizable text, and colour never the only carrier of meaning.',
  steps:['Tab through the module without a mouse','Check the focus indicator stays visible','Spot-check contrast on suspect text/background pairs','Zoom to 200% and check nothing breaks','Check anything colour-coded also has a label or shape']},
 '3.3.2':{look:'Captions on video, transcripts for audio, alt text on meaningful images, tagged PDFs with a sensible reading order. Re-verified live in Stage 3, not just claimed.',
  steps:['Play videos with captions on','Check transcripts exist for audio','Sample alt text on images that carry meaning','Open PDFs and check tags and reading order']},
 '3.3.3':{look:'Printed and projected material stays legible: minimum text size, clean typeface, sensible spacing.',
  steps:['View slides at a realistic viewing distance','Print a sample at intended size','Check the smallest text used']},
 '3.3.4':{look:'An accessibility statement telling learners what is supported, what is not, and how to request adjustments - visible before they commit.',
  steps:['Find the statement','Check it names supported needs and a request route','Check a learner can find it pre-purchase']},
 '3.4.1':{look:'Slides support the learning rather than being the script on screen: one idea per slide, honest charts, labelled diagrams.',
  steps:['Sample the deck for text walls','Check charts are honest (axes start sensibly, baselines shown)','Check diagrams are labelled well enough to stand alone']},
 '3.4.2':{look:'A consistent visual system: heading hierarchy, colour meanings and icon styles behave the same throughout.',
  steps:['Flick through the deck quickly - inconsistency jumps out at speed','Check colour is used to mean the same thing each time']},
 '3.4.3':{look:'Third-party images, fonts and media are licensed, with attribution wherever the licence requires it.',
  steps:['Ask for the licence record','Sample images and media against it','Check attributions appear where the licence demands']},
 '3.5.1':{look:'Examples, names and imagery are respectful and varied across protected characteristics - no stereotyped roles, no one-note representation of the workforce.',
  steps:['Scan names, roles and imagery across the material','Flag stereotyping (who is always the manager, who is always the learner)','Judge the material as the full range of its audience would']},
 '3.5.2':{look:'Where requirements differ across England, Wales, Scotland and NI, the material DECLARES which jurisdictions it covers. You check the declaration exists - never whether the law is stated correctly (A5).',
  steps:['Ask whether this subject differs across the four nations','If it does, find the scope declaration','Record findings only as "scope not declared" - never "law wrong"']},
 '4.1.1':{look:'Every assessment item maps to an outcome, and the bank as a whole covers every assessed outcome. This is why C-13 demands the FULL bank, not the served subset.',
  steps:['Work from the full bank supplied at C-13','Map a sample of items back to outcomes','Check every assessed outcome has items','Flag items that map to nothing']},
 '4.1.2':{look:'Items test at the outcome\'s level - application outcomes get scenario items, not recall - and nothing is a trick or ambiguous.',
  steps:['Sample items and classify each against its outcome\'s level','Sit the items yourself - ambiguity shows up fast','Flag trick wording, double negatives, two defensible answers']},
 '4.1.3':{look:'The pass mark comes with a stated rationale and setting method. "Industry standard 80%" with no reasoning is a number, not a justification.',
  steps:['Find the stated pass mark','Find how it was set and by whom','Judge whether the rationale connects to the outcomes\' stakes']},
 '4.2.1':{look:'Retakes are meaningful: pools or randomisation mean a resitting learner faces different items, and the retake policy is stated.',
  steps:['Compare bank size against items served per attempt','Check what a retake actually draws','Check the retake policy is published']},
 '4.2.2':{look:'Where humans mark, there are rubrics and some form of standardisation between markers.',
  steps:['Check rubrics exist for each marked task','Check how markers are kept consistent (sampling, moderation, calibration)']},
 '4.3.1':{look:'The certificate carries everything it should - learner, activity, hours, date, provider - plus a unique ID that can be verified. Check against the specimen from C-14.',
  steps:['Check every content element against the specimen','Check the ID scheme is unique per certificate','Check the ID resolves to a live verification route']},
 '4.3.2':{look:'Nothing on the certificate implies regulated status, a licence to practise, or more than the outcomes deliver. Read it as a sceptical employer would.',
  steps:['Read the certificate cold, as an employer','Flag "qualified", "licensed", "regulated", official-looking crests','Compare the biggest words on it against the actual outcomes']},
 '4.3.3':{look:'The wording matches what was measured: attendance/participation if nothing was assessed, achievement only where a real assessment was passed.',
  steps:['Check whether the activity assesses learners','Match the certificate verb to that: attended vs achieved/passed','Flag achievement wording on unassessed activities']},
 '4.4.1':{look:'Anti-fraud controls proportionate to what the certificate is used for - a workplace-entry certificate needs more than an interest-only one.',
  steps:['Ask what the certificate is used for in the real world','List the controls in place (ID checks, proctoring, unique IDs)','Judge proportionality - both under- and over-engineering count']},
 '5.1.1':{look:'Structured feedback is collected from every cohort, covering at least: relevance, clarity, engagement, and learner confidence afterwards.',
  steps:['Check the feedback instrument exists (form, survey)','Confirm it runs every cohort, not occasionally','Check the four areas are actually asked about']},
 '5.1.2':{look:'Response rates and results are kept and could be produced at surveillance - not collected and discarded.',
  steps:['Ask for the most recent cohorts\' results','Check response rates are recorded','Check the data is retrievable, not anecdotal']},
 '5.2.1':{look:'For substantial activities, some genuine attempt to measure beyond satisfaction - pre/post checks, follow-up, workplace feedback. Proportionate to the activity\'s size.',
  steps:['Check whether anything beyond a smile-sheet is attempted','Judge proportionality against the activity\'s length and stakes']},
 '5.3.1':{look:'A documented loop from feedback to real change: a feedback item, a decision, a dated alteration to the material - with examples.',
  steps:['Ask for concrete examples of feedback-driven change','Check each example shows item, decision and dated change','A change log or version history is the ideal evidence']},
 '5.4.1':{look:'A complaints procedure a learner could actually find and use, with stated timescales.',
  steps:['Find it the way a learner would','Check the steps and response times are stated']},
 '5.4.2':{look:'A fair, published refund policy - unambiguous, findable before purchase, and not unfair in substance.',
  steps:['Find the policy pre-purchase','Check the terms are clear and specific','Flag terms a reasonable buyer would call unfair']},
 '5.4.3':{look:'Complaints are logged and the records could be produced.',
  steps:['Ask how complaints are recorded','Sample the log if any complaints exist']},
 '6.1.1':{look:'A real, accountable legal entity: registered, at a verifiable address, with a named responsible person.',
  steps:['Check Companies House (or the relevant register)','Match the registered address to the one used','Confirm a named accountable person exists']},
 '6.1.2':{look:'Professional indemnity insurance in force, plus public liability where anything is delivered in person. Certificates, not assurances.',
  steps:['Check the certificates from C-10: insurer, policy number, expiry, cover level','Check PL is present if any delivery is face-to-face','Check nothing expires before the accreditation term matters']},
 '6.1.3':{look:'Signed declarations from the principals covering convictions and regulatory findings. A disclosure is not an automatic fail - it routes to the scheme\'s governance process, not your sole call.',
  steps:['Check each principal has signed a declaration','If anything is disclosed, escalate through the governance route rather than judging alone']},
 '6.2.1':{look:'ICO registration where the law requires it, and a privacy notice that actually covers learner data - what is held, why, and for how long.',
  steps:['Search the ICO register for the entity','Read the privacy notice for learner-data coverage','Flag a notice that is clearly a generic template with no learner mention']},
 '6.2.2':{look:'Learner records held securely, and kept at least 3 years where learning is certificated - an employer may need to verify years later.',
  steps:['Ask where learner records live and who can access them','Check the stated retention period against the 3-year floor']},
 '6.3.1':{look:'Marketing claims about the activity and its recognition are true - no invented endorsements, no inflated outcomes.',
  steps:['Read the sales page against what you have actually assessed','Flag invented recognition ("approved by...") and outcome inflation']},
 '6.3.2':{look:'Our mark is used only for the accredited activity and only within the validity period - not spread across the provider\'s whole catalogue.',
  steps:['Check current mark usage on the site and materials','Confirm it is scoped to this activity only','Note the expiry date drives when usage must stop']},
 '6.3.3':{look:'Nothing anywhere implies the scheme verified or endorsed the truth of the content. The badge means "meets the CPD framework" - never "facts checked" (A5).',
  steps:['Search the marketing for "verified", "endorsed", "approved content"','Flag any wording that shifts content responsibility onto the scheme']},
 '6.4.1':{look:'The provider can actually deliver at the scale they advertise - people, platform, rooms.',
  steps:['Compare advertised availability with named staff and infrastructure','Flag obvious mismatches (a one-person team advertising unlimited daily cohorts)']},
 '6.4.2':{look:'If the provider stopped trading mid-course, there is a written plan for learners in flight: refunds, records access, a completion route.',
  steps:['Check a written continuity plan exists','Check it covers refunds, records and completion']},

 'C-01':{look:'You can actually get in, end to end: LMS codes work, joining links resolve, the venue plan opens. Test it now - a broken login discovered at assessment time wastes the whole allocation.',
  steps:['Log into the LMS with the supplied code','Follow every joining link','Open the venue plan if face-to-face']},
 'C-02':{look:'Everything the submission references is actually in the pack - scripts, decks, workbooks, module access. Anything referenced but missing is a No.',
  steps:['Inventory the pack against the submission list','Note anything referenced in the materials but not supplied']},
 'C-03':{look:'The provider\'s self-assessment matrix is present with a row for every indicator. Presence and completeness only - judging the quality of their answers is Stage 2\'s job.',
  steps:['Open the matrix','Check no indicator row is blank','Do not judge answer quality here']},
 'C-04':{look:'The SME sign-off document is present: name, credentials, date. (Verifying the credentials are real happens at 1.2.2 - here you only need the document.)',
  steps:['Check the document exists with all three elements']},
 'C-05':{look:'The signed warranty of accuracy and lawfulness is present and covers this version.',
  steps:['Check the signature, the date and the version it names']},
 'C-06':{look:'The CPD-hours calculation document is present and itemised. (The arithmetic itself is checked at 1.4.2 and re-derived at Stage 4.)',
  steps:['Check the document exists and is broken into components']},
 'C-07':{look:'A CV for every single person named anywhere in the materials as educator, author or designer - not just the headline trainer.',
  steps:['List every name credited in the materials','Match each to a CV in the pack','Chase any gap before assessment starts']},
 'C-08':{look:'The readability method and score are stated somewhere in the submission. (Whether the score is any good is 3.1.2\'s job.)',
  steps:['Find the stated method and score']},
 'C-09':{look:'All three policies are in the pack: complaints, refunds, privacy notice.',
  steps:['Check each of the three is present','Note any that are links rather than documents - links rot']},
 'C-10':{look:'Insurance certificates are present and in date.',
  steps:['Check each certificate\'s expiry','Check PL is included if delivery is in person']},
 'C-11':{look:'The conflict-of-interest screen has been run on both allocations: does the lead or moderator know the provider, have financial links, or past employment there?',
  steps:['Screen the lead assessor','Screen the moderator','Record the check - a clean screen is still a record']},
 'C-12':{look:'The assessment fee has cleared. It is payable regardless of outcome - that separation is what keeps the decision clean.',
  steps:['Confirm payment has actually cleared, not just been invoiced']},
 'C-13':{look:'The FULL exam/question bank - every item that exists - not the subset an LMS serves in one sitting, and not one randomly-sampled paper. Coverage checks at 4.1 are meaningless against a partial bank.',
  steps:['Ask the provider to export the entire pool','Compare the count against what the LMS says it draws per attempt','Treat one paper or one export screen as incomplete']},
 'C-14':{look:'A specimen or mock-up of the certificate exactly as a learner would receive it - the real template with sample data, not a design concept that differs from production.',
  steps:['Ask for the production template with sample data','Check it is what learners actually get, not a marketing mock']},

 'MOD-1':{look:'Every score cites evidence you could locate yourself. A score that just "looks fine" is exactly the kind moderation exists to catch.',
  steps:['Sample scores across all six standards','Find each cited piece of evidence yourself','Bounce back anything you cannot locate from the citation alone']},
 'MOD-2':{look:'Every N/A has a stated reason, and the indicator genuinely cannot apply (mode not used, no assessment, no certificate) - N/A is never a shortcut past an awkward check.',
  steps:['Read every N/A reason','Check each against the case setup','Bounce back any N/A of convenience']},
 'MOD-3':{look:'Mandatory indicators are binary: Met or Not met. Any partial credit sitting on a gate is a scoring error, full stop.',
  steps:['Scan every [M] row','Bounce back any that is not exactly Met or Not met']},
 'MOD-4':{look:'The borderline Met/Partially-met calls - the ones that decide whether a case lands above or below a threshold - re-scored blind from the evidence.',
  steps:['Pick a sample of borderline calls','Re-score each from the evidence without looking at the lead\'s score','Compare and resolve any difference with the lead']},
 'MOD-5':{look:'Every failed gate double-checked: is the finding solid, and did the provider get their notice promptly rather than at decision time?',
  steps:['Re-check the evidence behind each Not-met gate','Check a provider notice was issued promptly for each','Flag any failure sitting unnotified']},
 'MOD-6':{look:'The draft decision is arithmetic: gates plus points against the published thresholds. Recompute it yourself - if your result differs from the tool\'s, stop and resolve before anything is issued.',
  steps:['Recompute: all gates met? points percentage against 85% / 70%?','Compare with the computed verdict','Any mismatch stops the process until resolved']}
};

export const CAUSES=['Point-of-entry statement missing or incomplete','Outcomes list missing, unmapped or unassessable','SME sign-off missing or uncredentialed','Version, owner and review cycle not stated','Hours derivation - claimed vs derived','Placeholders, drafts or broken routes in the material','Platform accessibility','Assessment design does not match the outcomes','Marketing or certificate claims overreach','Policies pack - complaints, refunds, privacy','Legal entity, insurance or named principal','Sources not attributed'];

export const SV_SUBMISSIONS=[
 ['SV-01','Learner feedback data for the period received - response rates and results retained (5.1.2)'],
 ['SV-02','Complaints log and outcomes received (5.4.3)'],
 ['SV-03','Change log received - material changes were notified within 28 days (C4)'],
 ['SV-04','Current version of all accredited materials received']
];

export const SV_DRIFT=[
 ['SV-05','1.2 review cycle actually run - reviewed-on dates current, named owner still in post (1.2.4)'],
 ['SV-06','Marketing claims sampled - accurate, in scope, nothing implies the scheme verified content (6.3, A5)'],
 ['SV-07','Materials sampled against the accredited version - no unnotified material drift'],
 ['SV-08','Feedback-to-change loop still running - at least one evidenced change from learner feedback (5.3.1)'],
 ['SV-09','Scheme-collected learner feedback reviewed with the provider (feedback dashboard) - negative trends already addressed, or named actions set now']
];

export const SV_DUE_WINDOW=60;
export const SV_RENEWAL_WINDOW=90;
export const DEFERRAL_DAYS=56;

export function guidanceFor(key){return GUIDANCE[key]||null;}

export function sourcesFor(key){
  if(SOURCES[key])return SOURCES[key];
  var m=/^(\d\.\d)\.\d$/.exec(key);
  if(m&&SOURCES[m[1]])return SOURCES[m[1]];
  if(/^C-\d+$/.test(key))return SOURCES['COMP'];
  if(/^MOD-\d+$/.test(key))return SOURCES['MOD'];
  if(/^SV-\d+$/.test(key))return SOURCES['SV'];
  return null;
}
